apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
    tags.datadoghq.com/env: gunicorn  # Add here for unified service tagging
    tags.datadoghq.com/service: gunicorn-dd # Add here for unified service tagging
    tags.datadoghq.com/version: 1.0.0 # Add here for unified service tagging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      annotations:
        admission.datadoghq.com/python-lib.version: v2.9.2 # Add here for APM lib injection
      labels:
        app: hello-world
        admission.datadoghq.com/enabled: "true" # Add here for APM lib injection
        tags.datadoghq.com/env: gunicorn  # Add here for unified service tagging
        tags.datadoghq.com/service: gunicorn-dd # Add here for unified service tagging
        tags.datadoghq.com/version: 1.0.0 # Add here for unified service tagging
    spec:
      containers:
      - name: hello-world
        image: jonlimpw/gunicorn-dd:build1
        ports:
        - containerPort: 8000